apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ms-secrets
data:
  PORT: {{ .Values.secrets.PORT | b64enc | quote }}

  DB_TYPE: {{ .Values.secrets.DB_TYPE | b64enc | quote }}
  DB_USER_NAME: {{ .Values.secrets.DB_USER_NAME | b64enc | quote }}
  DB_POST_NAME: {{ .Values.secrets.DB_POST_NAME | b64enc | quote }}
  DB_HOST: {{ .Values.secrets.DB_HOST | b64enc | quote }}
  DB_PORT: {{ .Values.secrets.DB_PORT | b64enc | quote }}
  DB_USER: {{ .Values.secrets.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  DB_AUTHSOURCE: {{ .Values.secrets.DB_AUTHSOURCE | b64enc | quote }}

  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}


  KAFKA_BROKER: {{ .Values.secrets.KAFKA_BROKER | b64enc | quote }}
  KAFKA_SASL_USERNAME: {{ .Values.secrets.KAFKA_SASL_USERNAME | b64enc | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.secrets.KAFKA_SASL_PASSWORD | b64enc | quote }}


  REDIS_HOST: {{ .Values.secrets.REDIS_HOST | b64enc | quote }}
  REDIS_PORT: {{ .Values.secrets.REDIS_PORT | b64enc | quote }}
  REDIS_USERNAME: {{ .Values.secrets.REDIS_USERNAME | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | b64enc | quote }}
  REDIS_DEFAULT_DB: {{ .Values.secrets.REDIS_DEFAULT_DB | b64enc | quote }}